name: gpu_training
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - cyrus-sasl=2.1.28
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.4
  - fontconfig=2.14.1
  - freetype=2.13.3
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20250127.0
  - libcups=2.4.2
  - libcurl=8.12.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - openldap=2.6.4
  - openssl=3.0.16
  - overrides=7.4.0
  - packaging=24.2
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=25.0
  - platformdirs=3.10.0
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.12.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtconsole=5.6.1
  - qtdeclarative=6.7.3
  - qtpy=2.4.1
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - send2trash=1.8.2
  - setuptools=75.8.0
  - sip=6.10.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - albucore==0.0.34
      - albumentationsx==2.0.13
      - annotated-types==0.7.0
      - augly==1.0.0
      - bitsandbytes==0.45.5
      - cachetools==5.5.2
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==2.21.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - dotenv==0.9.9
      - eval-type-backport==0.2.2
      - filelock==3.13.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gdown==5.2.0
      - geojson==3.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.2
      - google-auth==2.39.0
      - googleapis-common-protos==1.70.0
      - gritlm==1.0.2
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - iopath==0.1.10
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - labelbox==6.10.0
      - lbox-clients==1.1.2
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mteb==1.36.38
      - multidict==6.2.0
      - multiprocess==0.70.16
      - mypy==1.10.1
      - mypy-extensions==1.1.0
      - narwhals==1.34.1
      - networkx==3.3
      - nlpaug==1.1.3
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - pandas==2.2.3
      - pillow==12.0.0
      - plotly==6.0.1
      - polars==1.26.0
      - portalocker==3.2.0
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.3
      - python-dotenv==1.2.1
      - python-magic==0.4.27
      - pytrec-eval-terrier==0.5.7
      - pytz==2025.2
      - regex==2024.11.6
      - rich==14.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentence-transformers==4.0.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - simsimd==6.5.3
      - smmap==5.0.2
      - soxr==1.0.0
      - strenum==0.4.15
      - stringzilla==4.4.1
      - sympy==1.13.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - wandb==0.19.9
      - xxhash==3.5.0
      - yarl==1.19.0
prefix: /home/jowatson/.conda/envs/gpu_training
